version: "3.8"

services:
  skillmanager:
    build:
      dockerfile: ./skillmanager.Dockerfile
    restart: unless-stopped
    volumes:
      - "./volumes/skillmanager/config:/usr/src/skillmanager/src/config"
      - "./volumes/skillmanager/skills:/usr/src/skillmanager/src/skills"
    ports:
      - "3000:3000"

  frontend:
    build:
      dockerfile: ./frontend.Dockerfile
    restart: unless-stopped
    ports:
      - "12102:80"
