version: "3.8"

services:
  skillmanager:
    build:
      dockerfile: ./skillmanager.Dockerfile
    restart: unless-stopped
    networks:
      - gecko
    volumes:
      - "./volumes/skillmanager/config:/usr/src/skillmanager/src/config"
      - "./volumes/skillmanager/skills:/usr/src/skillmanager/src/skills"

  frontend:
    build:
      dockerfile: ./frontend.Dockerfile
    restart: unless-stopped
    depends_on:
      - skillmanager
    networks:
      - gecko
    ports:
      - "12102:80"

networks:
  gecko: